# Generated by Django 5.0.3 on 2024-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_verified_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="images/200x200.jpg", null=True, upload_to="images/"
            ),
        ),
    ]
