# Generated by Django 5.0.3 on 2024-03-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "russian_title",
                    models.CharField(
                        default="", max_length=50, verbose_name="Russian title"
                    ),
                ),
                (
                    "english_title",
                    models.CharField(
                        default="", max_length=50, verbose_name="English title"
                    ),
                ),
                (
                    "poster",
                    models.CharField(
                        default="", max_length=250, verbose_name="Poster ref"
                    ),
                ),
                ("rating", models.FloatField(verbose_name="Rating")),
                (
                    "anime_type",
                    models.CharField(default="", max_length=50, verbose_name="Type"),
                ),
                (
                    "episodes",
                    models.CharField(
                        default="", max_length=10, verbose_name="Episodes"
                    ),
                ),
                (
                    "status",
                    models.CharField(default="", max_length=50, verbose_name="Status"),
                ),
                (
                    "genre",
                    models.CharField(default="", max_length=50, verbose_name="Genre"),
                ),
                (
                    "release",
                    models.CharField(default="", max_length=50, verbose_name="Release"),
                ),
                (
                    "studio",
                    models.CharField(default="", max_length=50, verbose_name="Studio"),
                ),
                (
                    "age_restrictions",
                    models.CharField(
                        default="", max_length=10, verbose_name="Age restrictions"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        default="", max_length=50, verbose_name="Duration"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("screens", models.JSONField(verbose_name="Screens")),
                (
                    "trailer",
                    models.CharField(
                        default="", max_length=250, verbose_name="Trailer"
                    ),
                ),
                (
                    "animego",
                    models.CharField(
                        default="", max_length=250, verbose_name="AnimeGo ref"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="", max_length=250, verbose_name="Source ref"
                    ),
                ),
            ],
            options={
                "verbose_name": "Anime",
                "verbose_name_plural": "Animes",
            },
        ),
    ]
