# Generated by Django 5.0.3 on 2024-03-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimePreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "russian_title",
                    models.CharField(
                        default="", max_length=50, verbose_name="Russian itle"
                    ),
                ),
                (
                    "english_title",
                    models.CharField(
                        default="", max_length=50, verbose_name="English title"
                    ),
                ),
                (
                    "poster",
                    models.CharField(
                        default="", max_length=250, verbose_name="Poster ref"
                    ),
                ),
                ("rating", models.FloatField(verbose_name="Rating")),
                (
                    "animego",
                    models.CharField(
                        default="", max_length=250, verbose_name="AnimeGo ref"
                    ),
                ),
            ],
            options={
                "verbose_name": "AnimePreview",
                "verbose_name_plural": "AnimesPreviews",
            },
        ),
    ]
