# Generated by Django 5.0.3 on 2024-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0002_animepreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        default="", max_length=250, verbose_name="AnimeGo url"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="", max_length=250, verbose_name="Source url"
                    ),
                ),
            ],
            options={
                "verbose_name": "AnimeModel",
                "verbose_name_plural": "AnimeModels",
            },
        ),
        migrations.DeleteModel(
            name="Anime",
        ),
    ]
