# Generated by Django 5.0.3 on 2024-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0003_animemodel_delete_anime"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnimePreview",
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="source",
            field=models.CharField(
                default="", max_length=250, null=True, verbose_name="Source url"
            ),
        ),
    ]
