# Generated by Django 5.0.3 on 2024-03-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0004_delete_animepreview_alter_animemodel_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="english_name",
            field=models.CharField(
                default="", max_length=250, verbose_name="English name"
            ),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="poster",
            field=models.CharField(
                default="", max_length=250, verbose_name="Poster url"
            ),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="rating",
            field=models.FloatField(default=1, verbose_name="Rating"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animemodel",
            name="russian_name",
            field=models.CharField(
                default="", max_length=250, verbose_name="Russian name"
            ),
        ),
    ]
