# Generated by Django 5.0.3 on 2024-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0005_animemodel_english_name_animemodel_poster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="english_name",
            field=models.CharField(
                default="", max_length=250, null=True, verbose_name="English name"
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="poster",
            field=models.CharField(
                default="", max_length=250, null=True, verbose_name="Poster url"
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="rating",
            field=models.FloatField(null=True, verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="russian_name",
            field=models.CharField(
                default="", max_length=250, null=True, verbose_name="Russian name"
            ),
        ),
    ]
