# Generated by Django 5.0.3 on 2024-05-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0006_alter_animemodel_english_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="user_id",
            field=models.IntegerField(default=1, verbose_name="User id"),
            preserve_default=False,
        ),
    ]
